---
- hosts: webservers
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    
    - name: Wait for 60 seconds
      pause:
        seconds: 60

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: dipinoar/nuevaimagen:latest
        source: pull
    
    - name: Start Docker container
      docker_container:
        name: contenedor
        image: dipinoar/nuevaimagen:latest
        state: started
        published_ports:
          - "8099:8099"

  
    - name: Wait for 60 seconds
      pause:
        seconds: 60

    - name: Stop Docker container
      docker_container:
        name: contenedor
        state: stopped

    - name: Remove Docker container
      docker_container:
        name: contenedor
        state: absent

    - name: Remove Docker image
      docker_image:
        name: dipinoar/nuevaimagen:latest
        state: absent

    - name: Uninstall Docker
      apt:
        name: docker.io
        state: absent

    - name: Verify Docker uninstallation
      shell: sudo apt list --installed | grep -i docker
      register: docker_uninstalled
      ignore_errors: true

    - name: Print Docker uninstallation status
      debug:
        msg: "Docker is {{ 'uninstalled' if docker_uninstalled.rc != 0 else 'still installed' }}"

    
