---
- hosts: webservers
  become: true
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the Hello1 service
      docker_container:
        name: cicdEjemplo
        image: "dipinoar/cicdEJEMPLO:01"
        state: started
        published_ports:
          - "0.0.0.0:8099:8099"
      tags: hello1
  
